apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: yingchiaochen-k8s-tls 
spec:
  secretName: yingchiaochen-k8s
  issuerRef: 
    name: letsencrypt-prod 
    kind: ClusterIssuer
  commonName: yingchiaochen.org
  dnsNames: 
    - yingchiaochen.org
    - www.yingchiaochen.org
  acme:
    config:
      - http01: 
          ingressClass: nginx  
        domains: 
          - yingchiaochen.org
          - www.yingchiaochen.org  
